# secrets.toml

# Sua chave da API OpenAI
OPENAI_API_KEY = "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"

# Assistant OpenAI
OPENAI_ASSISTANT = "asst_VNrnSqfLZtGXz3Jz6XqyVGZT"

# Sua chave da API ElevenLabs
ELEVEN_LABS_API_KEY = "10d4a9bea8391979c3bcfa5360bac06e"

